#ifndef KEYBOARD_H
#define KEYBOARD_H

/**
 * @brief Subscribes and enables keyboard interrupts.
 * @return 0 on success, 1 otherwise.
 */
int kbc_subscribe_int();

/**
 * @brief Unsubscribes keyboard interrupts.
 * @return 0 on success, 1 otherwise.
 */
int kbc_unsubscribe_int();


/**
 * @brief Assembles and prints the scancode.
 * @details This function processes the scancode, determining whether it is a make or break code 
 * and prints it accordingly. It handles both single and multi-byte scancodes.
 */
void kbd_print_scancode_assemble();

/**
 * @brief Reads a scancode from the keyboard controller.
 * @details This function reads a scancode from the keyboard controller's output buffer, handling 
 * possible errors such as timeout or parity errors.
 * @return 0 on success, 1 otherwise.
 */
int(kbc_read)();

/**
 * @brief Keyboard interrupt handler.
 * @details This function handles the interrupts generated by the keyboard, reading the scancodes 
 * and handling possible errors.
 */
void (kbc_ih)();

#endif
