#ifndef MOUSE_H
#define MOUSE_H

#include <lcom/lcf.h>

/**
 * @brief Subscribes and enables mouse interrupts.
 * @return 0 on success, 1 otherwise.
 */
int(mouse_subscribe_int)();

/**
 * @brief Unsubscribes mouse interrupts.
 * @return 0 on success, 1 otherwise.
 */
int(mouse_unsubscribe_int)();

/**
 * @brief Mouse interrupt handler.
 * @details This function handles the interrupts generated by the mouse, reading the packets and 
 * handling possible errors.
 */
void (mouse_ih)();

/**
 * @brief Prints the mouse packet.
 * @details This function prints the contents of the mouse packet, after ensuring synchronization 
 * with the mouse data stream.
 */
void print_mouse_packet();

/**
 * @brief Writes an argument to the mouse.
 * @param argument The argument to be written to the mouse.
 * @return 0 on success, 1 otherwise.
 */
int(write_argument_to_mouse)(uint8_t argument);

/**
 * @brief Enables the mouse in stream mode.
 * @return 0 on success, 1 otherwise.
 */
int(enable_mouse)();

/**
 * @brief Disables the mouse.
 * @return 0 on success, 1 otherwise.
 */
int(disable_mouse)();

/**
 * @brief Retrieves the mouse coordinates.
 * @details This function processes the mouse packets to update the mouse coordinates, taking into 
 * account possible synchronization issues.
 */
void get_mouse_coordinates();

/**
 * @brief Moves the cursor based on mouse input.
 * @details This function updates the cursor position on the screen based on the mouse's delta 
 * values and ensures the cursor stays within the screen boundaries.
 */
void move_cursor();

#endif
